/**
 * @module actionTypes
 */

export default {
	BOOT: 'BOOT',
	LINK_DWELL: 'LINK_DWELL',
	ABANDON_START: 'ABANDON_START',
	ABANDON_END: 'ABANDON_END',
	LINK_CLICK: 'LINK_CLICK',
	FETCH_START: 'FETCH_START',
	FETCH_END: 'FETCH_END',
	FETCH_COMPLETE: 'FETCH_COMPLETE',
	FETCH_FAILED: 'FETCH_FAILED',
	PREVIEW_DWELL: 'PREVIEW_DWELL',
	PREVIEW_SHOW: 'PREVIEW_SHOW',
	PREVIEW_CLICK: 'PREVIEW_CLICK',
	SETTINGS_SHOW: 'SETTINGS_SHOW',
	SETTINGS_HIDE: 'SETTINGS_HIDE',
	SETTINGS_CHANGE: 'SETTINGS_CHANGE',
	EVENT_LOGGED: 'EVENT_LOGGED',
	STATSV_LOGGED: 'STATSV_LOGGED'
};
